spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowMaxAge: 3600
      routes:

        - id: profile-service
          uri: https://aibert-profile-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/profile/**, /api/admin/users/** , /api/auth/verify-otp, /api/auth/resend-verification, /api/auth/register , /internal/users/**

        - id: auth-service
          uri: https://aibert-auth-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/auth/**

        - id: academic-service
          uri: https://aibert-academic-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/academic/**, /api/v1/subjects, /api/v1/subjects/**

        - id: task-service
          uri: https://aibert-task-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/tasks/**

        - id: recommendation-service
          uri: https://aibert-recommendation-servic-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/recommendations/**

        - id: engineplanning-service
          uri: https://aibert-engineplaning-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/planning/**

        - id: social-service
          uri: https://aibert-social-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/social/**

        - id: gamification-service
          uri: https://aibert-gamification-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/gamification/**, /api/v1/gamification/**

        - id: notification-service
          uri: https://aibert-notification-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/stats/**

        - id: stats-service
          uri: https://aibert-stats-service-qa.yellowwave-cb2d91fc.centralus.azurecontainerapps.io
          predicates:
            - Path=/api/stats/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:secretLocalParaDesarrolloMuyLargoMinimo32Chars}

